---
- name: Compute cluster members
  ansible.builtin.set_fact:
    _target_hostaddrs: "{{ _target_members + _target_iphosts + _target_revhosts }}"
  vars:
    _target_hosts: "{{ _target_members | map(_split_with, ':') | map('first') }}"
    _target_inventory: "{{ _target_hosts | select('in', _fwdaddrs) }}"
    _target_inventory_addrs: "{{ _target_inventory | map('extract', _fwdaddrs) }}"
    _target_host_addrs: "{{ _target_hosts | ansible.utils.ipaddr }}"
    _target_addrs: "{{ _target_inventory_addrs + _target_host_addrs }}"
    _target_iphosts: "{{ _target_addrs | map(_map_format, '%s:' + mongodb_port) }}"
    _target_revaddrs: "{{ _target_addrs | select('in', _revaddrs) }}"
    _target_revnames: "{{ _target_revaddrs | map('extract', _revaddrs) }}"
    _target_revhosts: "{{ _target_revnames | map(_map_format, '%s:' + mongodb_port) }}"
  tags: skip_ansible_lint
