---
- name: Reconfigure replica set
  hosts: all
  vars:
    _hosts1: "{{ play_hosts[:1] }}"
    _hosts2: "{{ play_hosts[:2] }}"
    _hosts3: "{{ play_hosts[-3:] }}"
    _hosts4: "{{ play_hosts[:4] }}"
    _hosts5: "{{ play_hosts[:2] + play_hosts[-3:] }}"
    _hosts6: "{{ play_hosts[:6] }}"
    _hosts7: "{{ play_hosts[:7] }}"
  tasks:
    - name: Manage python interpreter
      tags: always
      block:
        - name: Set base facts
          ansible.builtin.set_fact:
            _reconfigure1_failed: false
            _reconfigure2_failed: false
            _reconfigure4_failed: false
            _reconfigure6_failed: false

        - name: Create virtualenv
          ansible.builtin.tempfile:
            state: directory
            prefix: .virtualenv
            path: "~"
          register: _virtualenv_tmpdir
          changed_when: false

        - name: Initialize virtualenv
          ansible.builtin.pip:
            name:
              - pymongo
              - python-gnupg
            virtualenv: "{{ _virtualenv_tmpdir.path }}/venv"
          changed_when: false

        - name: Change python interpreter
          ansible.builtin.set_fact:
            ansible_python_interpreter: "{{ _virtualenv_tmpdir.path }}/venv/bin/python"

    - name: Test replicaset reconfiguration scenarios
      block:
        - name: Deploy 3 node cluster
          when: inventory_hostname in _hosts3
          block:
            - name: Deploy 3 node cluster
              ansible.builtin.set_fact:
                _config_members: "{{ _members | map(_map_format, '%s:' + _port) | list }}"
              vars:
                _port: "{{ mongodb_port | default('27017') }}"
                _map_format: 'nephelaiio.plugins.map_format'
                _addr_attrs: ['ansible_default_ipv4', 'address']
                _addresses: "{{ _hosts3 | map('extract', hostvars, _addr_attrs) }}"
                _members: "{{ _addresses | list }}"

            - name: Configure cluster members
              ansible.builtin.include_role:
                name: pokerops.mongodb
              vars:
                mongodb_replicaset_members: "{{ _config_members }}"
                mongodb_votes_group: "_replicaset_votes_up_three"
                mongodb_non_votes_group: "_replicaset_non_votes_up_three"
                mongodb_voting_group: "_replicaset_voting_up_three"
                mongodb_priority_group: "_replicaset_priority_up_three"
                mongodb_non_priority_group: "_replicaset_non_priority_up_three"
                mongodb_compliant_group: "_replicaset_compliant_up_three"
                mongodb_non_compliant_group: "_replicaset_non_compliant_up_three"
                mongodb_non_voting_group: "_replicaset_non_voting_up_three"
                mongodb_alien_group: "_replicaset_alien_up_three"
                mongodb_non_alien_group: "_replicaset_non_alien_up_three"
                mongodb_member_group: "_replicaset_member_up_three"
                mongodb_failed_group: "_replicaset_failed_up_three"

            - name: Query existing MongoDB replicaset members
              community.mongodb.mongodb_shell:
                eval: "rs.status().members"
                mongo_cmd: "{{ mongodb_shell | default(omit) }}"
              register: _query_members
              changed_when: false

            - name: Set replicaset member facts
              ansible.builtin.set_fact:
                _existing_members: "{{ _query_members.transformed_output | map(attribute='name') }}"

            - name: Debug replicaset members
              ansible.builtin.debug:
                var: _existing_members

            - name: Check cluster members
              ansible.builtin.assert:
                that: _config_members | difference(_existing_members) | length == 0

        - name: Attempt 2 node cluster scale down
          when: inventory_hostname in _hosts2
          block:
            - name: Scale down to 2 node cluster
              ansible.builtin.include_role:
                name: pokerops.mongodb
              vars:
                _map_format: 'nephelaiio.plugins.map_format'
                _addr_attrs: ['ansible_default_ipv4', 'address']
                _addresses: "{{ _hosts2 | map('extract', hostvars, _addr_attrs) }}"
                _members: "{{ _addresses | list }}"
                mongodb_replicaset_members: "{{ _members | map(_map_format, '%s:' + mongodb_port) | list }}"
                mongodb_votes_group: "_replicaset_votes_up_two"
                mongodb_non_votes_group: "_replicaset_non_votes_up_two"
                mongodb_voting_group: "_replicaset_voting_up_two"
                mongodb_priority_group: "_replicaset_priority_up_two"
                mongodb_non_priority_group: "_replicaset_non_priority_up_two"
                mongodb_compliant_group: "_replicaset_compliant_up_two"
                mongodb_non_compliant_group: "_replicaset_non_compliant_up_two"
                mongodb_non_voting_group: "_replicaset_non_voting_up_two"
                mongodb_alien_group: "_replicaset_alien_up_two"
                mongodb_non_alien_group: "_replicaset_non_alien_up_two"
                mongodb_member_group: "_replicaset_member_up_two"
                mongodb_failed_group: "_replicaset_failed_up_two"
          rescue:
            - name: Set result facts
              ansible.builtin.set_fact:
                _reconfigure2_failed: true
          always:
            - name: Fail on broken replicaset member configuration
              ansible.builtin.assert:
                that: _reconfigure2_failed
                fail_msg: "broken replicaset member configuration operation must fail"

        - name: Scale up to 5 node cluster
          when: inventory_hostname in _hosts5
          block:
            - name: Scale up to 5 node cluster
              ansible.builtin.set_fact:
                _config_members: "{{ _members | map(_map_format, '%s:' + _port) | list }}"
              vars:
                _port: "{{ mongodb_port | default('27017') }}"
                _map_format: 'nephelaiio.plugins.map_format'
                _addr_attrs: ['ansible_default_ipv4', 'address']
                _addresses: "{{ _hosts5 | map('extract', hostvars, _addr_attrs) }}"
                _members: "{{ _addresses | list }}"

            - name: Configure cluster members
              ansible.builtin.include_role:
                name: pokerops.mongodb
              vars:
                mongodb_replicaset_members: "{{ _config_members }}"
                mongodb_votes_group: "_replicaset_votes_up_five"
                mongodb_non_votes_group: "_replicaset_non_votes_up_five"
                mongodb_voting_group: "_replicaset_voting_up_five"
                mongodb_priority_group: "_replicaset_priority_up_five"
                mongodb_non_priority_group: "_replicaset_non_priority_up_five"
                mongodb_compliant_group: "_replicaset_compliant_up_five"
                mongodb_non_compliant_group: "_replicaset_non_compliant_up_five"
                mongodb_non_voting_group: "_replicaset_non_voting_up_five"
                mongodb_alien_group: "_replicaset_alien_up_five"
                mongodb_non_alien_group: "_replicaset_non_alien_up_five"
                mongodb_member_group: "_replicaset_member_up_five"
                mongodb_failed_group: "_replicaset_failed_up_five"

            - name: Query existing MongoDB replicaset members
              community.mongodb.mongodb_shell:
                eval: "rs.status().members"
                mongo_cmd: "{{ mongodb_shell | default(omit) }}"
              register: _query_members
              changed_when: false

            - name: Set replicaset member facts
              ansible.builtin.set_fact:
                _existing_members: "{{ _query_members.transformed_output | map(attribute='name') }}"

            - name: Debug replicaset members
              ansible.builtin.debug:
                var: _existing_members

            - name: Check cluster members
              ansible.builtin.assert:
                that: _config_members | difference(_existing_members) | length == 0

        - name: Attempt 4 node cluster scale down
          when: inventory_hostname in _hosts4
          block:
            - name: Scale down to 4 node cluster
              ansible.builtin.include_role:
                name: pokerops.mongodb
              vars:
                _map_format: 'nephelaiio.plugins.map_format'
                _addr_attrs: ['ansible_default_ipv4', 'address']
                _addresses: "{{ _hosts4 | map('extract', hostvars, _addr_attrs) }}"
                _members: "{{ _addresses | list }}"
                mongodb_replicaset_members: "{{ _members | map(_map_format, '%s:' + mongodb_port) | list }}"
          rescue:
            - name: Set result facts
              ansible.builtin.set_fact:
                _reconfigure4_failed: true
          always:
            - name: Fail on broken replicaset member configuration
              ansible.builtin.assert:
                that: _reconfigure4_failed
                fail_msg: "broken replicaset member configuration operation must fail"

        - name: Scale up to 7 node cluster
          when: inventory_hostname in _hosts7
          block:
            - name: Scale up to 7 node cluster
              ansible.builtin.set_fact:
                _config_members: "{{ _members | map(_map_format, '%s:' + _port) | list }}"
              vars:
                _port: "{{ mongodb_port | default('27017') }}"
                _map_format: 'nephelaiio.plugins.map_format'
                _addr_attrs: ['ansible_default_ipv4', 'address']
                _addresses: "{{ _hosts7 | map('extract', hostvars, _addr_attrs) }}"
                _members: "{{ _addresses | list }}"

            - name: Configure cluster members
              ansible.builtin.include_role:
                name: pokerops.mongodb
              vars:
                mongodb_replicaset_members: "{{ _config_members }}"
                mongodb_votes_group: "_replicaset_votes_up_seven"
                mongodb_non_votes_group: "_replicaset_non_votes_up_seven"
                mongodb_voting_group: "_replicaset_voting_up_seven"
                mongodb_priority_group: "_replicaset_priority_up_seven"
                mongodb_non_priority_group: "_replicaset_non_priority_up_seven"
                mongodb_compliant_group: "_replicaset_compliant_up_seven"
                mongodb_non_compliant_group: "_replicaset_non_compliant_up_seven"
                mongodb_non_voting_group: "_replicaset_non_voting_up_seven"
                mongodb_alien_group: "_replicaset_alien_up_seven"
                mongodb_non_alien_group: "_replicaset_non_alien_up_seven"
                mongodb_member_group: "_replicaset_member_up_seven"
                mongodb_failed_group: "_replicaset_failed_up_seven"

            - name: Query existing MongoDB replicaset members
              community.mongodb.mongodb_shell:
                eval: "rs.status().members"
                mongo_cmd: "{{ mongodb_shell | default(omit) }}"
              register: _query_members
              changed_when: false

            - name: Set replicaset member facts
              ansible.builtin.set_fact:
                _existing_members: "{{ _query_members.transformed_output | map(attribute='name') }}"

            - name: Debug replicaset members
              ansible.builtin.debug:
                var: _existing_members

            - name: Check cluster members
              ansible.builtin.assert:
                that: _config_members | difference(_existing_members) | length == 0

        - name: Attempt 6 node cluster scale down
          when: inventory_hostname in _hosts6
          block:
            - name: Scale down to 6 node cluster
              ansible.builtin.include_role:
                name: pokerops.mongodb
              vars:
                _map_format: 'nephelaiio.plugins.map_format'
                _addr_attrs: ['ansible_default_ipv4', 'address']
                _addresses: "{{ _hosts6 | map('extract', hostvars, _addr_attrs) }}"
                _members: "{{ _addresses | list }}"
                mongodb_replicaset_members: "{{ _members | map(_map_format, '%s:' + mongodb_port) | list }}"
          rescue:
            - name: Set result facts
              ansible.builtin.set_fact:
                _reconfigure6_failed: true
          always:
            - name: Fail on broken replicaset member configuration
              ansible.builtin.assert:
                that: _reconfigure6_failed
                fail_msg: "broken replicaset member configuration operation must fail"

        - name: Scale down to 5 node cluster
          when: inventory_hostname in _hosts5
          block:
            - name: Scale down to 5 node cluster
              ansible.builtin.set_fact:
                _config_members: "{{ _members | map(_map_format, '%s:' + _port) | list }}"
              vars:
                _port: "{{ mongodb_port | default('27017') }}"
                _map_format: 'nephelaiio.plugins.map_format'
                _addr_attrs: ['ansible_default_ipv4', 'address']
                _addresses: "{{ _hosts5 | map('extract', hostvars, _addr_attrs) }}"
                _members: "{{ _addresses | list }}"

            - name: Configure cluster members
              ansible.builtin.include_role:
                name: pokerops.mongodb
              vars:
                mongodb_replicaset_members: "{{ _config_members }}"
                mongodb_votes_group: "_replicaset_votes_down_five"
                mongodb_non_votes_group: "_replicaset_non_votes_down_five"
                mongodb_voting_group: "_replicaset_voting_down_five"
                mongodb_priority_group: "_replicaset_priority_down_five"
                mongodb_non_priority_group: "_replicaset_non_priority_down_five"
                mongodb_compliant_group: "_replicaset_compliant_down_five"
                mongodb_non_compliant_group: "_replicaset_non_compliant_down_five"
                mongodb_non_voting_group: "_replicaset_non_voting_down_five"
                mongodb_alien_group: "_replicaset_alien_down_five"
                mongodb_non_alien_group: "_replicaset_non_alien_down_five"
                mongodb_member_group: "_replicaset_member_down_five"
                mongodb_failed_group: "_replicaset_failed_down_five"

            - name: Query existing MongoDB replicaset members
              community.mongodb.mongodb_shell:
                eval: "rs.status().members"
                mongo_cmd: "{{ mongodb_shell | default(omit) }}"
              register: _query_members
              changed_when: false

            - name: Set replicaset member facts
              ansible.builtin.set_fact:
                _existing_members: "{{ _query_members.transformed_output | map(attribute='name') }}"

            - name: Debug replicaset members
              ansible.builtin.debug:
                var: _existing_members

            - name: Check cluster members
              ansible.builtin.assert:
                that: _config_members | difference(_existing_members) | length == 0

        - name: Scale down to 3 node cluster
          when: inventory_hostname in _hosts3
          block:
            - name: Scale down to 3 node cluster
              ansible.builtin.set_fact:
                _config_members: "{{ _members | map(_map_format, '%s:' + _port) | list }}"
              vars:
                _port: "{{ mongodb_port | default('27017') }}"
                _map_format: 'nephelaiio.plugins.map_format'
                _addr_attrs: ['ansible_default_ipv4', 'address']
                _addresses: "{{ _hosts3 | map('extract', hostvars, _addr_attrs) }}"
                _members: "{{ _addresses | list }}"

            - name: Configure cluster members
              ansible.builtin.include_role:
                name: pokerops.mongodb
              vars:
                mongodb_replicaset_members: "{{ _config_members }}"
                mongodb_votes_group: "_replicaset_votes_down_three"
                mongodb_non_votes_group: "_replicaset_non_votes_down_three"
                mongodb_voting_group: "_replicaset_voting_down_three"
                mongodb_priority_group: "_replicaset_priority_down_three"
                mongodb_non_priority_group: "_replicaset_non_priority_down_three"
                mongodb_compliant_group: "_replicaset_compliant_down_three"
                mongodb_non_compliant_group: "_replicaset_non_compliant_down_three"
                mongodb_non_voting_group: "_replicaset_non_voting_down_three"
                mongodb_alien_group: "_replicaset_alien_down_three"
                mongodb_non_alien_group: "_replicaset_non_alien_down_three"
                mongodb_member_group: "_replicaset_member_down_three"
                mongodb_failed_group: "_replicaset_failed_down_three"

            - name: Query existing MongoDB replicaset members
              community.mongodb.mongodb_shell:
                eval: "rs.status().members"
                mongo_cmd: "{{ mongodb_shell | default(omit) }}"
              register: _query_members
              changed_when: false

            - name: Set replicaset member facts
              ansible.builtin.set_fact:
                _existing_members: "{{ _query_members.transformed_output | map(attribute='name') }}"

            - name: Debug replicaset members
              ansible.builtin.debug:
                var: _existing_members

            - name: Check cluster members
              ansible.builtin.assert:
                that: _config_members | difference(_existing_members) | length == 0

        - name: Attempt 1 node cluster scale down
          when: inventory_hostname in _hosts1
          block:
            - name: Attempt 1 node cluster scale down
              ansible.builtin.include_role:
                name: pokerops.mongodb
              vars:
                _map_format: 'nephelaiio.plugins.map_format'
                _addr_attrs: ['ansible_default_ipv4', 'address']
                _addresses: "{{ _hosts1 | map('extract', hostvars, _addr_attrs) }}"
                _members: "{{ _addresses | list }}"
                mongodb_replicaset_members: "{{ _members | map(_map_format, '%s:' + mongodb_port) | list }}"
                mongodb_votes_group: "_replicaset_votes_down_one"
                mongodb_non_votes_group: "_replicaset_non_votes_down_one"
                mongodb_voting_group: "_replicaset_voting_down_one"
                mongodb_priority_group: "_replicaset_priority_down_one"
                mongodb_non_priority_group: "_replicaset_non_priority_down_one"
                mongodb_compliant_group: "_replicaset_compliant_down_one"
                mongodb_non_compliant_group: "_replicaset_non_compliant_down_one"
                mongodb_non_voting_group: "_replicaset_non_voting_down_one"
                mongodb_alien_group: "_replicaset_alien_down_one"
                mongodb_non_alien_group: "_replicaset_non_alien_down_one"
                mongodb_member_group: "_replicaset_member_down_one"
                mongodb_failed_group: "_replicaset_failed_down_one"
          rescue:
            - name: Set result facts
              ansible.builtin.set_fact:
                _reconfigure1_failed: true
          always:
            - name: Fail on broken replicaset member configuration
              ansible.builtin.assert:
                that: _reconfigure1_failed
                fail_msg: "broken replicaset member configuration operation must fail"

      always:
        - name: Destroy virtualenv
          ansible.builtin.file:
            path: "{{ _virtualenv_tmpdir.path }}"
            state: absent
          changed_when: false
