---
name: molecule

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 5 * * 5"

defaults:
  run:
    working-directory: "pokerops.mongodb"

jobs:
  molecule:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - hold
          - install
          - ufw
          - replicaset
          - votes
        image:
          - ubuntu2004
          - ubuntu2204
          - debian11
          - debian12
          - rockylinux9
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4
        with:
          path: "pokerops.mongodb"

      - name: Set up python 3
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Update ubuntu repositories
        run: sudo apt-get update

      - name: Install make
        run: sudo apt-get install -y make

      - name: Install dependencies
        run: make install

      - name: Debug test environment
        run: make debug

      - name: Run molecule tests
        run: make test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DOCKER_IMAGE: ${{ matrix.image }}
          MOLECULE_COMMAND: "/lib/systemd/systemd"
          MOLECULE_SCENARIO: ${{ matrix.scenario }}
